config/routes.rb
Rails.application.routes.draw do
  resources :ephemeris
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'ephemeris#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ephemeri.rb
class Ephemeri < ApplicationRecord
    mount_uploader :imagen, ImagenUploader
    enum category: %i[musical deportiva noticia tecnologia cultura otra]
    scope :by_categoria, ->(input) { where('categoria LIKE ?', input) }

       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ephemeris_controller.rb
class EphemerisController < ApplicationController
  before_action :set_ephemeri, only: %i[ show edit update destroy ]

  # GET /ephemeris or /ephemeris.json
  def index
     #binding.pry
     search = params['search'] # esto trae el parametro de busqueda
     @ephemeris = search.present? ? Ephemeri.by_categoria(search['categoria']) : Ephemeri.all
    
  end

  # GET /ephemeris/1 or /ephemeris/1.json
  def show
  end

  # GET /ephemeris/new
  def new
    @ephemeri = Ephemeri.new
  end

  # GET /ephemeris/1/edit
  def edit
  end

  # POST /ephemeris or /ephemeris.json
  def create
    @ephemeri = Ephemeri.new(ephemeri_params)

    respond_to do |format|
      if @ephemeri.save
        format.html { redirect_to @ephemeri, notice: "Ephemeri was successfully created." }
        format.json { render :show, status: :created, location: @ephemeri }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ephemeri.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ephemeris/1 or /ephemeris/1.json
  def update
    respond_to do |format|
      if @ephemeri.update(ephemeri_params)
        format.html { redirect_to @ephemeri, notice: "Ephemeri was successfully updated." }
        format.json { render :show, status: :ok, location: @ephemeri }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ephemeri.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ephemeris/1 or /ephemeris/1.json
  def destroy
    @ephemeri.destroy
    respond_to do |format|
      format.html { redirect_to ephemeris_url, notice: "Ephemeri was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ephemeri
      @ephemeri = Ephemeri.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ephemeri_params
      params.require(:ephemeri).permit(:fecha, :categoria, :comentario, :imagen, :created_at)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ephemeris_helper.rb
module EphemerisHelper
end

app/views/ephemeris/_form.html.erb
<%= form_with(model: ephemeri) do |form| %>
  <% if ephemeri.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ephemeri.errors.count, "error") %> prohibited this ephemeri from being saved:</h2>

      <ul>
        <% ephemeri.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :fecha %>
    <%= form.datetime_select :fecha %>
  </div>

  <div class="field">
    <%= form.label :categoria %>
    <%= form.select(:categoria, Ephemeri.categories.keys.map {|category| [category.titleize]})  %>
  </div>

  <div class="field">
    <%= form.label :comentario %>
    <%= form.text_field :comentario %>
  </div>

  <div class="field">
    <%= form.label :imagen %>
    <%= form.file_field :imagen %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ephemeris/edit.html.erb
<h1>Editing Ephemeri</h1>

<%= render 'form', ephemeri: @ephemeri %>

<%= link_to 'Show', @ephemeri %> |
<%= link_to 'Back', ephemeris_path %>

app/views/ephemeris/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ephemeris</h1>

<%= form_for :search, url: ephemeris_path, method: :get do |f| %>
  <%= f.text_field :categoria %>
  <%= f.submit "Search" %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Fecha</th>
      <th>Categoria</th>
      <th>Comentario</th>
      <th>Imagen</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ephemeris.each do |ephemeri| %>
      <tr>
        <td><%= ephemeri.fecha %></td>
        <td><%= ephemeri.categoria %></td>
        <td><%= ephemeri.comentario %></td>
        <td><%= image_tag(ephemeri.imagen.url, alt: 'Imagen', resize: "100x100", size: '100') %></td>
        <td><%= link_to 'Show', ephemeri %></td>
        <td><%= link_to 'Edit', edit_ephemeri_path(ephemeri) %></td>
        <td><%= link_to 'Destroy', ephemeri, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ephemeri', new_ephemeri_path %>

app/views/ephemeris/new.html.erb
<h1>New Ephemeri</h1>

<%= render 'form', ephemeri: @ephemeri %>

<%= link_to 'Back', ephemeris_path %>

app/views/ephemeris/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fecha:</strong>
  <%= @ephemeri.fecha %>
</p>

<p>
  <strong>Categoria:</strong>
  <%= @ephemeri.categoria %>
</p>

<p>
  <strong>Comentario:</strong>
  <%= @ephemeri.comentario %>
</p>

<p>
  <strong>Imagen:</strong>
  <%= image_tag(@ephemeri.imagen.url, alt: 'Imagen', resize: "100x100", size: '100') %>
</p>

<%= link_to 'Edit', edit_ephemeri_path(@ephemeri) %> |
<%= link_to 'Back', ephemeris_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ephemeride</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>